// examples/nextjs-no-ssr/src/app/page.tsx
"use client";

import { ExButton } from "@expressthat-auth/ui-react";

// Client Component — ExButton is mounted in the browser only, no server rendering.
export default function HomePage() {
  return (
    <main style={{ padding: "2rem", fontFamily: "sans-serif" }}>
      <h1>Next.js Example (client-side only, no SSR)</h1>
      <p>ExButton is a client-side web component from @expressthat-auth/ui-react.</p>
      <ExButton label="Click Me" variant="primary" onExClick={() => alert("clicked!")} />
    </main>
  );
}

// examples/vue/src/App.vue
<script setup lang="ts">
import { ExButton } from "@expressthat-auth/ui-vue";

const handleClick = () => alert("clicked!");
</script>

<template>
  <main style="padding: 2rem; font-family: sans-serif">
    <h1>Vue 3 Example (Vite, no SSR)</h1>
    <p>Renders ExButton from @expressthat-auth/ui-vue as a client-side web component.</p>
    <ExButton label="Click Me" variant="primary" @ex-click="handleClick" />
  </main>
</template>
