// examples/vue/src/App.vue
<script setup lang="ts">
import { ExTestButton } from "@expressthat-auth/ui-vue";

const handleClick = () => alert("clicked!");
</script>

<template>
  <main style="padding: 2rem; font-family: sans-serif">
    <h1>Vue 3 Example (Vite, no SSR)</h1>
    <p>Renders ExTestButton from @expressthat-auth/ui-vue as a client-side web component.</p>
    <ExTestButton label="Click Me" variant="primary" @ex-test-click="handleClick" />
  </main>
</template>

// examples/angular/src/app/app.component.ts
import { Component } from "@angular/core";
import { ExTestButton } from "@expressthat-auth/ui-angular";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [ExTestButton],
  templateUrl: "./app.component.html",
})
export class AppComponent {
  handleClick() {
    alert("clicked!");
  }
}

<main style="padding: 2rem; font-family: sans-serif">
  <h1>Angular 21 Example (no SSR)</h1>
  <p>Renders EXTestButton from @expressthat-auth/ui-angular as a web component wrapper.</p>
  <ex-test-button label="Click Me" variant="primary" (exTestClick)="handleClick()"></ex-test-button>
</main>
