// examples/vue/src/App.vue
<script setup lang="ts">
import { ExButton } from "@expressthat-auth/ui-vue";

const handleClick = () => alert("clicked!");
</script>

<template>
  <main style="padding: 2rem; font-family: sans-serif">
    <h1>Vue 3 Example (Vite, no SSR)</h1>
    <p>Renders ExButton from @expressthat-auth/ui-vue as a client-side web component.</p>
    <ExButton label="Click Me" variant="primary" @ex-click="handleClick" />
  </main>
</template>

// examples/react/src/App.tsx
import { ExButton } from "@expressthat-auth/ui-react";

export default function App() {
  return (
    <main style={{ padding: "2rem", fontFamily: "sans-serif" }}>
      <h1>React Example (Vite, no SSR)</h1>
      <p>Renders ExButton from @expressthat-auth/ui-react as a client-side web component.</p>
      <ExButton label="Click Me" variant="primary" onExClick={() => alert("clicked!")} />
    </main>
  );
}
